@extends('core::layouts.marketing')

@section('title', 'Terms of service — ' . config('app.name'))
@section('meta_description', 'Terms of service for ' . config('app.name') . '.')
@section('robots', 'index, follow')

{{--
    ⚠ NOT LEGAL ADVICE, AND NOT REVIEWED BY A LAWYER.

    This is a plain-English starting point covering the terms this product
    actually needs: what the service is, what the customer owns, the AI-accuracy
    disclaimer (the important one for this product — minutes are a business
    record and customers must understand they carry review responsibility),
    billing behaviour, and termination.

    Before taking real payments, Ryan should have this reviewed against the
    Consumer Protection Act and ECTA. The billing and cancellation clauses below
    describe what the code genuinely does, so they are accurate — but "accurate"
    and "enforceable" are different tests.

    Effective date and company details come from config('site.*') so they are not
    buried in this template.
--}}

@section('content')
    <div class="container-xl py-6">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h1 class="mb-1">Terms of service</h1>
                <p class="text-secondary mb-5">
                    Effective {{ \Illuminate\Support\Carbon::parse(config('site.legal_effective_date'))->toFormattedDayDateString() }}
                </p>

                <div class="mn-minutes">
                    <h2>1. Who we are</h2>
                    <p>
                        {{ config('app.name') }} ("the service") is operated by
                        {{ config('site.company_name') }}, based in {{ config('site.company_country') }}.
                        You can reach us at
                        <a href="mailto:{{ config('site.contact_email') }}">{{ config('site.contact_email') }}</a>.
                    </p>
                    <p>
                        By creating an account or using the service you agree to these terms. If you
                        are agreeing on behalf of a company, you confirm you are authorised to do so.
                    </p>

                    <h2>2. What the service does</h2>
                    <p>
                        You provide meeting material — a transcript, notes, or a document. The service
                        uses a large language model to produce structured meeting minutes from it, in
                        a defined nine-section format. You can then edit those minutes, regenerate
                        individual sections, and export them.
                    </p>

                    <h2>3. Accuracy — please read this one</h2>
                    <p>
                        <strong>The minutes are generated by an AI model and may contain errors.</strong>
                        They are a draft produced from the material you supplied, not a certified
                        record. The model can misattribute a statement, misread a figure, miss
                        something that was said, or misinterpret an ambiguous passage.
                    </p>
                    <p>
                        You are responsible for reviewing minutes before you rely on them, circulate
                        them, or treat them as a record of your organisation's decisions. This matters
                        especially where minutes carry legal or governance weight — board resolutions,
                        statutory meetings, regulated proceedings, or anything that may be produced in
                        a dispute. Every section is editable precisely so that you can correct it.
                    </p>
                    <p>
                        We provide the service "as is" and do not warrant that generated minutes are
                        accurate, complete, or fit for any particular purpose.
                    </p>

                    <h2>4. Your content stays yours</h2>
                    <p>
                        You keep all rights in the transcripts, notes and documents you upload, and in
                        the minutes generated from them. You grant us only the permission needed to
                        run the service: to store your material, to send it to our language model
                        provider in order to generate your minutes, and to display it back to you and
                        your workspace members.
                    </p>
                    <p>
                        <strong>We do not use your content to train models.</strong> We do not sell it,
                        and we do not share it with anyone other than the infrastructure and model
                        providers needed to deliver the service. See our
                        <a href="{{ route('site.privacy') }}">privacy policy</a> for the detail.
                    </p>

                    <h2>5. Your account</h2>
                    <p>
                        Keep your password to yourself and tell us promptly if you think someone else
                        has access to your account. You are responsible for what happens under your
                        account and for the people you invite into your workspace.
                    </p>
                    <p>
                        One person may not share a single account with others — that is what workspace
                        seats are for.
                    </p>

                    <h2>6. Acceptable use</h2>
                    <p>Please do not:</p>
                    <ul>
                        <li>upload material you do not have the right to upload, including recordings
                            made without the consent required in your jurisdiction;</li>
                        <li>upload material unlawful where you are, or content designed to cause harm;</li>
                        <li>attempt to break, overload, probe or reverse-engineer the service;</li>
                        <li>resell the service, or use it to build a competing product;</li>
                        <li>create multiple accounts to get around free-plan limits.</li>
                    </ul>
                    <p>
                        Recording consent is worth a specific mention: laws on recording meetings vary,
                        and obtaining the necessary consent from participants is your responsibility,
                        not ours.
                    </p>

                    <h2>7. Plans, payment and cancellation</h2>
                    <ul>
                        <li>
                            The free plan is permanent and requires no card. It includes a limited number
                            of generations per month.
                        </li>
                        <li>
                            Paid plans are billed in advance, monthly or annually, through our payment
                            provider Paystack. We never see or store your full card details.
                        </li>
                        <li>
                            Your generation allowance resets on your own billing anniversary.
                        </li>
                        <li>
                            You may cancel at any time. You keep your paid features until the end of the
                            period you have already paid for, then move to the free plan. We do not
                            refund part-used periods.
                        </li>
                        <li>
                            If a renewal payment fails, your workspace continues working for
                            {{ config('billing.grace_period_days') }} days so you can fix the payment
                            method. After that it moves to the free plan.
                        </li>
                        <li>
                            <strong>A downgrade never deletes your data.</strong> Your meetings,
                            transcripts and minutes remain available; free-plan limits apply to new
                            generations.
                        </li>
                        <li>
                            We may change prices. Existing subscriptions keep their agreed price for the
                            current period, and we will give reasonable notice before a change applies to
                            your renewal.
                        </li>
                    </ul>

                    <h2>8. Availability</h2>
                    <p>
                        We aim to keep the service available and to look after your data, but we do not
                        offer a formal uptime guarantee on standard plans. Maintenance, third-party
                        outages (including our language model provider) and faults can interrupt the
                        service. Please keep your own copies of anything you cannot afford to lose —
                        export is available on every plan.
                    </p>

                    <h2>9. Limits on our liability</h2>
                    <p>
                        To the extent the law allows, we are not liable for indirect or consequential
                        loss, lost profits, lost business, or loss arising from your reliance on
                        generated minutes without reviewing them. Where liability cannot be excluded,
                        it is limited to the amount you paid us in the twelve months before the claim.
                    </p>
                    <p>
                        Nothing here limits rights you have under South African consumer law that
                        cannot lawfully be limited.
                    </p>

                    <h2>10. Ending the arrangement</h2>
                    <p>
                        You can stop using the service and delete your account whenever you like. We
                        may suspend or close an account that breaches these terms, or where required by
                        law — and we will tell you why unless we are prevented from doing so.
                    </p>
                    <p>
                        After account deletion, your data is retained for
                        {{ config('site.data_retention_days') }} days in case you ask us to restore it,
                        and then permanently erased.
                    </p>

                    <h2>11. Changes to these terms</h2>
                    <p>
                        We may update these terms. For material changes we will give notice by email or
                        in the application before they take effect. Continuing to use the service after
                        that means you accept the updated terms.
                    </p>

                    <h2>12. Governing law</h2>
                    <p>
                        These terms are governed by the laws of {{ config('site.company_country') }}, and
                        its courts have jurisdiction over any dispute.
                    </p>

                    <h2>13. Contact</h2>
                    <p>
                        Questions about these terms:
                        <a href="mailto:{{ config('site.contact_email') }}">{{ config('site.contact_email') }}</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection
