<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 10pt; color: #1a1a1a; }
        h1 { font-size: 17pt; margin: 0 0 2pt 0; }
        .meta { color: #666; font-size: 9pt; margin-bottom: 14pt; }
        .mn-minutes h2 { font-size: 12.5pt; color: #1F4E79; border-bottom: 1px solid #ccc; padding-bottom: 2pt; margin-top: 14pt; }
        .mn-minutes h3 { font-size: 11pt; margin: 8pt 0 3pt 0; }
        .mn-minutes h4 { font-size: 9pt; text-transform: uppercase; letter-spacing: .4pt; color: #666; margin: 6pt 0 2pt 0; }
        table.mn-kv { border-collapse: collapse; }
        .mn-kv th { text-align: left; color: #555; font-weight: bold; padding: 2pt 10pt 2pt 0; vertical-align: top; width: 120pt; }
        .mn-kv td { padding: 2pt 0; }
        table.mn-actions { width: 100%; border-collapse: collapse; font-size: 8.5pt; }
        .mn-actions th, .mn-actions td { border: 0.5pt solid #999; padding: 3pt 4pt; text-align: left; vertical-align: top; }
        .mn-actions th { background: #1F4E79; color: #fff; }
        .mn-na { color: #999; font-style: italic; }
        .mn-priority-high { color: #b02a37; font-weight: bold; }
        .mn-priority-medium { color: #997404; }
        .mn-priority-low { color: #146c43; }
        .mn-quality { background: #fff8e1; padding: 6pt 10pt; margin-top: 10pt; }
        ul { margin: 3pt 0 6pt 14pt; padding: 0; }
        li { margin-bottom: 2pt; }
        p { margin: 3pt 0; }
    </style>
</head>
<body>
    <h1>{{ $meeting->title ?? 'Meeting Minutes' }}</h1>
    <div class="meta">
        {{ $meeting->meeting_date?->format('j F Y') ?? '' }}
        · Generated by {{ config('app.name') }} {{ $meeting->created_at->format('Y-m-d') }}
    </div>
    {!! $meeting->rendered_html !!}
</body>
</html>
